### ISSUE TITLE
Endpoint Checklist

### ISSUE THREAD

**Issue by MikuAuahDark** [DarkEnergyProcessor/NPPS4#1]
All possible endpoints can be found in `common/svapi` folder, regardless if they're used or not. Endpoints marked in **bold** are curently stubs. Some endpoints maybe marked as **bold** and checked. This depends on their "completeness".

* [ ] `achievement/initialAccomplishedList`
* [ ] `achievement/pagingAccomplishedList`
* [ ] `achievement/pagingUnaccomplishList`
* [ ] `achievement/rewardOpen`
* [ ] `achievement/rewardOpenAll`
* [x] `achievement/unaccomplishList` - List unaccomplished achievement by their filter category ID.
* [ ] **`ad/changeAd`**
* [x] `album/albumAll` - List all acquired cards sequentially. \*
* [x] `album/seriesAll` - List all acquired cards by their series.
* [ ] **`announce/checkState`**
* [ ] `area/addReward`
* [ ] `area/list`
* [ ] `arena/cancelDreamSession`
* [ ] `arena/cheerUnitDeck`
* [ ] `arena/dailyRanking`
* [ ] `arena/dreamLiveEnd`
* [ ] `arena/dreamLiveGameOver`
* [ ] `arena/dreamLiveStart`
* [ ] `arena/matchLiveContinue`
* [ ] `arena/matchLiveEnd`
* [ ] `arena/matchLiveGameOver`
* [ ] `arena/matchLiveStart`
* [ ] `arena/matching`
* [ ] `arena/moveUpStage`
* [ ] `arena/privateMatchLiveEnd`
* [ ] `arena/privateMatchLiveGameOver`
* [ ] `arena/privateMatchLiveStart`
* [ ] `arena/privateMatching`
* [ ] `arena/read`
* [ ] `arena/recoveryAutoPlayableCount`
* [ ] `arena/rivalLiveContinue`
* [ ] `arena/rivalLiveEnd`
* [ ] `arena/rivalLiveGameOver`
* [ ] `arena/rivalLiveStart`
* [ ] `arena/sessionRanking`
* [ ] `arena/tierRanking`
* [ ] `arena/top`
* [x] `award/awardInfo` - Get all titles acquired by user.
* [x] `award/set` - Set active title of user.
* [x] `background/backgroundInfo` - Get all wallpapers acquired by user.
* [x] `background/set` - Set active wallpaper of user.
* [ ] **`banner/bannerList`** - Get currently available banners.
* [ ] `battle/battleInfo`
* [ ] `battle/endRoom`
* [ ] `battle/endWait`
* [ ] `battle/gameover`
* [ ] `battle/liveEnd`
* [ ] `battle/liveStart`
* [ ] `battle/matching`
* [ ] `battle/startWait`
* [ ] `battle/top`
* [ ] `challenge/challengeInfo`
* [ ] `challenge/checkpoint`
* [ ] `challenge/continue`
* [ ] `challenge/finalize`
* [ ] `challenge/gameover`
* [ ] `challenge/init`
* [ ] `challenge/proceed`
* [ ] `challenge/retire`
* [ ] `challenge/status`
* [ ] `challenge/top`
* [ ] `class/commitChallengeMission`
* [ ] `class/competitionFinalLiveEnd`
* [ ] `class/competitionFinalLivePlay`
* [ ] `class/competitionGameover`
* [ ] `class/competitionGeneralRanking`
* [ ] `class/competitionHallOfFame`
* [ ] `class/competitionLiveEnd`
* [ ] `class/competitionLivePlay`
* [ ] `class/competitionOwnDeckRanking`
* [ ] `class/competitionReady`
* [ ] `class/competitionResult`
* [ ] `class/competitionSpectateLive`
* [ ] `class/competitionStartWait`
* [ ] `class/entryFinal`
* [ ] `class/entrySemifinal`
* [ ] `class/gameover`
* [ ] `class/livePlay`
* [ ] `class/liveResult`
* [ ] `class/selectCompetitionArea`
* [ ] `class/selectCompetitionPromise`
* [ ] `class/skipChallengeMission`
* [ ] `class/top`
* [ ] `class/voteFinal`
* [ ] `class/voteSemifinal`
* [ ] `comeback/achieveInfo`
* [ ] `common/checkNgword`
* [ ] `common/liveResume`
* [ ] `common/logger`
* [ ] `common/recoveryEnergy`
* [ ] `concert/liveContinue`
* [ ] `concert/liveEnd`
* [ ] `concert/liveGameOver`
* [ ] `concert/liveInit`
* [ ] `concert/livePartyList`
* [ ] `concert/liveStart`
* [ ] `concert/lootBoxPick`
* [ ] `concert/lootBoxReset`
* [ ] `concert/lootBoxTop`
* [ ] `concert/top`
* [ ] `costume/costumeList`
* [ ] `costume/costumeStatus`
* [ ] `costume/dressUp`
* [ ] `costume/makeCostume`
* [x] `download/additional` - Download single package ID by their package type.
* [x] `download/batch` - Download all packages specified by their package type.
* [ ] **`download/event`**
* [x] `download/getUrl` - Download single file (used in micro downloads).
* [ ] `download/luaDownload` \*
* [x] `download/update` - Perform download to update client version.
* [ ] `duel/assistLog`
* [ ] `duel/duelSubDeck`
* [ ] `duel/endRoom`
* [ ] `duel/endWait`
* [ ] `duel/fixTime`
* [ ] `duel/gameover`
* [ ] `duel/gpsMatch`
* [ ] `duel/leave`
* [ ] `duel/liveEnd`
* [ ] `duel/liveLog`
* [ ] `duel/livePolling`
* [ ] `duel/liveStart`
* [ ] `duel/matching`
* [ ] `duel/privateClose`
* [ ] `duel/privateCreate`
* [ ] `duel/privateJoin`
* [ ] `duel/privateLeave`
* [ ] `duel/privateMakeMatch`
* [ ] `duel/privateOpenMatch`
* [ ] `duel/privateStartWait`
* [ ] `duel/startWait`
* [ ] `duel/top`
* [ ] `duty/allUserMission`
* [ ] `duty/dutyInfo`
* [ ] `duty/endRoom`
* [ ] `duty/endWait`
* [ ] `duty/gameover`
* [ ] `duty/history`
* [ ] `duty/historyDetail`
* [ ] `duty/liveEnd`
* [ ] `duty/liveStart`
* [ ] `duty/matching`
* [ ] `duty/privateClose`
* [ ] `duty/privateCreate`
* [ ] `duty/privateJoin`
* [ ] `duty/privateJoinMatch`
* [ ] `duty/privateLeave`
* [ ] `duty/privateMakeMatch`
* [ ] `duty/privateStartWait`
* [ ] `duty/startWait`
* [ ] `duty/top`
* [ ] `effortPoint/selectLimitedBox`
* [ ] **`event/eventList`**
* [ ] `event/eventYellDeck`
* [ ] `eventscenario/open`
* [ ] `eventscenario/reward` - Give player reward after reading main story for the first time.
* [ ] `eventscenario/startup` - Start viewing event side story.
* [ ] **`eventscenario/status`** - List all unlocked event side story.
* [ ] `exchange/itemInfo`
* [ ] `exchange/owningPoint`
* [ ] `exchange/usePoint`
* [ ] `festival/continue`
* [ ] `festival/deckList`
* [ ] `festival/festivalInfo`
* [ ] `festival/gameover`
* [ ] `festival/liveReward`
* [ ] `festival/liveSetList`
* [ ] `festival/liveStart`
* [ ] `festival/missionStatus`
* [ ] `festival/top`
* [ ] `festival/updateLiveList`
* [ ] `freeLive/play`
* [ ] `friend/expel` - Remove user as friend.
* [ ] **`friend/list`** - List friends.
* [ ] `friend/request` - Send friend request to user.
* [ ] `friend/requestCancel` - Cancel friend request to user.
* [ ] `friend/response` - Accept or reject friend request.
* [ ] **`friend/search`** - Find user ID from their invite code.
* [ ] `gdpr/detail`
* [ ] **`gdpr/get`**
* [ ] `gdpr/update`
* [ ] `greet/delete` - Delete private message.
* [ ] `greet/user` - Send private message to user.
* [ ] `handover/abortTransfer` - Cancel SIF2 transfer migration.
* [ ] `handover/create`
* [ ] **`handover/exec`** - Perform account transfer using transfer passcode. \*
* [ ] `handover/kidCheck`
* [ ] `handover/kidDelete` - Unlink account from SIFID.
* [ ] `handover/kidHandover`
* [ ] `handover/kidInfo` - Check SIFID service status.
* [ ] `handover/kidRegister` - Link account to SIFID.
* [ ] `handover/kidStatus` - Check SIFID linkage status.
* [ ] `handover/reserveTransfer` - Generate SIF2 transfer code for SIF2 migration.
* [ ] `handover/start`
* [ ] `item/exchange`
* [ ] **`item/list`** - List all items.
* [ ] `item/useBuff`
* [ ] `item/useLotteryTicket`
* [ ] `item/useReinforceItem`
* [ ] `item/userRankUp`
* [ ] `klab_id/kidInitialAccomplishedList`
* [ ] `klab_id/kidPagingAccomplishedList`
* [ ] `klab_id/kidPagingUnaccomplishList`
* [ ] `klab_id/kidRewardOpen`
* [ ] `klab_id/kidRewardOpenAll`
* [ ] `klab_id/kidUnaccomplishList`
* [ ] `klab_id/sync`
* [ ] `klab_id/syncActivate`
* [ ] `klab_id/syncDeactivate`
* [ ] `lbonus/adReward`
* [x] `lbonus/execute` - Perform login bonus check. Give player login bonus and login-related goals if necessary.
* [ ] `live/continue`
* [ ] **`live/gameover`** - End live show.
* [ ] **`live/liveStatus`** - Get all available live show and their status. **Partially implemented.**
* [x] `live/partyList` - Get available guests. **Partially implemented. Only returns current user at the moment.**
* [x] `live/play` - Start live show. **Partially implemented. Does not consume LP at the moment.**
* [ ] **`live/preciseScore`** - Get live show play record.
* [ ] `live/publishPreciseScoreId`
* [ ] `live/reward` - Finish live show.
* [ ] **`live/schedule`** - Get limited-time live show list.
* [x] **`liveicon/liveiconInfo`** - Get available live show icons.
* [x] **`livese/liveseInfo`** - Get available live show tap sound effects.
* [x] `login/login` - Perform login authentication.
* [ ] **`login/topInfo`** - Get more user-related information.
* [ ] **`login/topInfoOnce`** - Get more user-related information.
* [x] `login/unitList` - Get list of starter character card. **Performed in account creation.**
* [x] `login/unitSelect` - Select starter character card. **Performed in account creation.**
* [ ] `marathon/marathonInfo`
* [ ] `marathon/top`
* [ ] `multiunit/multiunitscenarioStatus`
* [ ] `multiunit/scenarioReward`
* [ ] `multiunit/scenarioStartup`
* [x] `museum/info` - Get information about memories gallery.
* [ ] `navigation/specialCutin` \*
* [ ] `notice/noticeFriendGreeting`
* [ ] `notice/noticeFriendVariety`
* [ ] **`notice/noticeMarquee`** - Get in-game notice that shown as moving text.
* [ ] `notice/noticeUserGreetingHistory`
* [ ] `online/deck`
* [ ] `online/exhibitionResult`
* [ ] `online/info`
* [ ] `online/play`
* [ ] `online/playExhibition`
* [ ] `online/result`
* [ ] `payment/history`
* [ ] `payment/month`
* [ ] `payment/processLog`
* [ ] **`payment/productList`**
* [ ] `payment/receipt` - Process payment.
* [ ] `payment/setBirth`
* [ ] `payment/subscriptionRead`
* [ ] `personalnotice/agree` - Accept warning/infraction notice.
* [ ] `personalnotice/clearCache`
* [ ] **`personalnotice/get`** - Get user warning/infraction.
* [ ] `platformAccount/connectAccounts`
* [ ] `platformAccount/disconnectAccounts`
* [ ] `platformAccount/handover`
* [ ] `platformAccount/isConnectedLlAccount`
* [ ] `platformAccount/isConnectedPfAccount`
* [ ] `preciseScore/manualUpdate`
* [ ] **`profile/cardRanking`** - Get most loved cards by user. **Stub implementation currently crashes client!**
* [ ] **`profile/liveCnt`** - Get amount of live show cleared by difficulty of user.
* [x] `profile/profileInfo` - Get user profile information.
* [x] `profile/profileRegister` - Set bio/introduction.
* [ ] `quest/continue`
* [ ] `quest/gameover`
* [ ] `quest/itemInfo`
* [ ] `quest/owningSeal`
* [ ] `quest/partyList`
* [ ] `quest/questInfo`
* [ ] `quest/questList`
* [ ] `quest/questReward`
* [ ] `quest/questStart`
* [ ] `quest/useSeal`
* [ ] `ranking/eventFriendLive`
* [ ] `ranking/eventFriendPlayer`
* [ ] `ranking/eventLive`
* [ ] `ranking/eventLiveDetail`
* [ ] `ranking/eventPlayer`
* [ ] `ranking/live`
* [ ] `ranking/player`
* [ ] `reward/adReward`
* [ ] `reward/exchange`
* [ ] `reward/exchangeList`
* [ ] `reward/open` - Receive single item in present box.
* [ ] `reward/openAll` - Receive up to 1000 items in present box, when situation allows.
* [ ] `reward/rewardHistory` - List of present box history.
* [ ] **`reward/rewardList`** - Get list of items in present box.
* [ ] `reward/sellUnit`
* [ ] `reward/useLotteryTicket`
* [ ] `rlive/continue`
* [ ] `rlive/gameover`
* [ ] `rlive/lot`
* [ ] `rlive/play`
* [ ] `rlive/reward`
* [ ] `scenario/reward` - Give player reward after reading main story for the first time.
* [x] `scenario/scenarioStatus` - List all unlocked main story.
* [x] `scenario/startup` - Start viewing main story.
* [ ] **`secretbox/all`** - List all scouting banners.
* [ ] `secretbox/knapsackReset`
* [ ] `secretbox/knapsackSelect`
* [ ] `secretbox/multi` - Perform 10+1 scouting.
* [ ] `secretbox/pon` - Perform 1 scouting.
* [ ] `secretbox/selectPickUp`
* [ ] `secretbox/selectUnit`
* [ ] `secretbox/showDetail`
* [ ] `secretbox/stampDetail`
* [ ] `skit/skitInfo`
* [ ] `sns/addReward`
* [ ] `sns/getReward`
* [ ] `stamp/set`
* [ ] `stamp/stampInfo`
* [ ] `subscenario/reward` - Give player reward after reading character side story for the first time.
* [ ] `subscenario/startup` - Start viewing character side story.
* [ ] `subscenario/subscenarioStatus` - List all unlocked character side story.
* [x] `tos/tosAgree` - Agree to (updated) Terms of Service.
* [x] `tos/tosCheck` - Check if user already agreed to (updated) Terms of Service
* [x] `tutorial/progress` - Continue tutorial progression.
* [x] `tutorial/skip` - Skip the entire tutorial.
* [ ] **`unit/accessoryAll`** - Get accessory.
* [ ] `unit/accessoryMaterialAll`
* [ ] `unit/accessoryTab`
* [x] `unit/activate` - Move unit out from waiting room.
* [ ] `unit/changeDelegate`
* [ ] `unit/createAccessory`
* [ ] `unit/deck`
* [x] `unit/deckInfo` - Get all team formation.
* [x] `unit/deckName` - Change team name.
* [ ] `unit/exchangePointRankUp` - Idolize card using stickers.
* [ ] `unit/favorite` - Mark unit as favorite.
* [ ] `unit/favoriteAccessory`
* [ ] `unit/maxLevelUp`
* [ ] `unit/merge` - Practice card.
* [ ] `unit/mergeAccessory`
* [ ] `unit/rankUp` - Idolize card using another (same) card.
* [x] `unit/removableSkillEquipment` - Add or remove School Idol Skills (SIS) from a card.
* [x] `unit/removableSkillInfo` - List all SIS information and which card uses which SIS.
* [ ] `unit/removableSkillRankUp`
* [ ] `unit/removableSkillSell`
* [ ] `unit/sale` - Remove card.
* [ ] `unit/saleAccessory`
* [x] `unit/setDisplayRank` - Toggle display card between idolized and unidolized form. Stats are unchanged.
* [x] `unit/supporterAll` - List all support cards.
* [x] `unit/unitAll` - List all cards (excluding support cards).
* [x] `unit/wait` - Move card to waiting room.
* [ ] `unit/wearAccessory`
* [ ] `user/abortDelete`
* [ ] `user/addFriendMax`
* [ ] `user/addUnitMax`
* [x] `user/changeName` - Change user name.
* [x] `user/changeNavi` - Change partner.
* [x] `user/getNavi` - Get current partner.
* [ ] `user/reserveDelete`
* [ ] `user/setBirth` - Set user birthday (only shown in JP client due to GDPR).
* [ ] `user/setNotification`
* [ ] **`user/setNotificationToken`** - _Unknown_. **Implementation currently crashes client.**
* [ ] `user/showAllItem`
* [x] `user/userInfo` - Get current user information.

\* indicates endpoint that's possibly unused.
