### ISSUE TITLE
Early Testing Phase Checklist

### ISSUE THREAD

**Issue by MikuAuahDark** [DarkEnergyProcessor/NPPS4#5]
Tracking issues that need to be resolved before NPPS4 enter its early testing phase (no ETA).
* [x] Registration, tutorial, entering home screen.
* [x] Achievement progression.
* [x] Collecting reward from achievement manually.
* [x] Live show.
* [x] Reading and clearing main story.
* [x] Reading and clearing side story.
* [x] Unit practice.
* [x] Unit special practice.
* [x] Remove unit.
* [x] Exchanging units between active and waiting room.
* [x] Collecting rewards from present box.
* [x] Scouting.
